#!/bin/bash

# Kerberos realm of the service admin key
# (empty for unsecured cluster)
REALM='ICS.MUNI.CZ'

# Keytab file of the service admin key
#KEYTAB='/etc/security/keytab/hbase.service.keytab'

# Kerberos principal of the service admin key
#PRINCIPAL="hbase/`hostname -f`@${REALM}"

# Internal directories, which should not be deleted
#RESERVED='NAMESPACE|default|hbase|hive|oozie'

# Perform real physical delete
# (check /var/tmp/perun-hadoop-hdfs* for additional cleanups)
#FORCE_DELETE=0
