include:
  - project: perun/common
    file: /templates/.gitlab-ci-template.yml

variables:
  # release from production branch instead of main
  RELEASE_FROM_PRODUCTION: 1
  PYTHON_FILES: 'send/pithia_portal send/ftps_generic send/bbmri_networks send/tinia send/feudal.py send/webcentrum_eosc send/umbraco_mu send/openstack_projects send/m365_cloud send/slack send/o365_groups_mu send/atlassian_mu send/bbmri_collections send/generic_send.py send/generic_sender.py send/send_lib.py send/scs_it4i'
