[project]
name = "perun-services"
version = "9.0.0"
requires-python = "==3.9"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}

[project.urls]
Repository = "https://gitlab.ics.muni.cz/perun/perun-idm/perun-services.git"
