#!/bin/bash

# Kerberos realm of the service admin key
# (empty for unsecured cluster)
# REALM=''

# Keytab file of the service admin key
#KEYTAB='/etc/security/keytab/nn.service.keytab'

# Kerberos principal of the service admin key
#PRINCIPAL="nn/`hostname -f`@${REALM}"

# Internal directories, which should not be deleted
#RESERVED='hbase|hdfs|hive|oozie|spark'

# Perform real physical delete
# (check /var/tmp/perun-hadoop-hdfs* for additional cleanups)
#FORCE_DELETE=0
