#!/usr/bin/env python3
import sys
import send_lib
from datetime import datetime
import re

SERVICE_NAME = "crocs_user_export"

send_lib.check_input_fields(sys.argv)

facility = sys.argv[1]
destination = sys.argv[2]
destination_type = send_lib.DESTINATION_TYPE_SERVICE_SPECIFIC if len(sys.argv) < 4 else sys.argv[3]

send_lib.check_destination_type_allowed(destination_type, send_lib.DESTINATION_TYPE_SERVICE_SPECIFIC)
send_lib.check_destination_format(destination, destination_type)

service_files_dir = send_lib.get_gen_folder(facility, SERVICE_NAME)

timestamp = datetime.now().strftime("%Y-%m-%d_%H.%M.%S")

send_lib.copy_files_to_directory(service_files_dir, destination + "/crocs-user-export-" + timestamp, re.compile(SERVICE_NAME))