#!/bin/bash

if [ -z "$SERVICE_NAME" ]; then
	echo 'Error: $SERVICE_NAME is not set' >&2
	exit 1;
fi

TIMEOUT="5400" #90s * 60 sec = 1.5h
TIMEOUT_KILL="60" # 60 sec to kill after timeout

FACILITY_NAME=$1
DESTINATION=$2
DESTINATION_TYPE=$3
KEY_PATH="`echo ~`/.ssh/id_rsa"
TRANSPORT_COMMAND="ssh -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -o GSSAPIKeyExchange=no -o ConnectTimeout=5  -i $KEY_PATH"

if [ -f "/etc/perun/services/${SERVICE_NAME}/${SERVICE_NAME}.conf" ]; then
	. "/etc/perun/services/${SERVICE_NAME}/${SERVICE_NAME}.conf"
fi

#use standard time and language settings (ASCII)
export LC_TIME="C"
export LANG="C"

SLAVE_COMMAND="/opt/perun/bin/perun"
SERVICE_FILES_BASE_DIR="`pwd`/../gen/spool"
SERVICE_FILES_DIR="$SERVICE_FILES_BASE_DIR/$FACILITY_NAME/$SERVICE_NAME"

#dir which contains special configuration for this destination (this dir may not exist)  ==IT MUST BE ABSOLUTE PATH (because of double -C in tar command)==
SERVICE_FILES_FOR_DESTINATION="$SERVICE_FILES_DIR/_destination/$DESTINATION"

#Just safety check. This should not happen.
if [ ! -d "$SERVICE_FILES_DIR" ]; then echo '$SERVICE_FILES_DIR: '$SERVICE_FILES_DIR' is not a directory' >&2 ; exit 1; fi

#unless specific configuration for destination exists use common configuration for all destination
[ -d "$SERVICE_FILES_FOR_DESTINATION" ] || SERVICE_FILES_FOR_DESTINATION="$SERVICE_FILES_DIR/_destination/all"

#prepare additional parameters for tar if using configuration per destination
TAR_OPTIONS_CONF_PER_DESTINATION=""
[ -d "$SERVICE_FILES_FOR_DESTINATION" ] && TAR_OPTIONS_CONF_PER_DESTINATION=" -C '${SERVICE_FILES_FOR_DESTINATION}' . "

#if there is no destination type, use default 'host'
if [ -z "$DESTINATION_TYPE" ]; then
	DESTINATION_TYPE="host"
fi

case $DESTINATION_TYPE in
	host)
		HOSTNAME="$DESTINATION"
		HOST="root@$DESTINATION"
		;;
	user@host)
		# Get the user name from the destination
		HOSTNAME=`echo $DESTINATION | sed -e 's/^.*@//'`
		HOST="$DESTINATION"
		;;
	user@host:port)
		HOST=`echo $DESTINATION | sed -e 's/:.*//'`
		HOSTNAME=`echo $HOST | sed -e 's/^.*@//'`
		PORT=`echo $DESTINATION | sed -e 's/^.*://'`
		;;
	url)
		HOSTNAME="$DESTINATION"
		HOST="$DESTINATION"
		TRANSPORT_COMMAND="curl -i -H Content-Type:application/tar -f -X PUT"
		;;
	email)
		echo "Destination type '$DESTINATION_TYPE' is not supported yet." >&2
		exit 1;
		;;
	*)
		echo "Unknown destination type '$DESTINATION_TYPE'." >&2
		exit 1;
		;;
esac

if [ -n "${PORT}" ]; then
	TRANSPORT_COMMAND="${TRANSPORT_COMMAND} -p ${PORT}"
fi

TMP_HOSTNAME_DIR="`mktemp -d /tmp/perun-send.XXXXXXXXXX`"
if [ $? -ne 0 ]; then
	echo "Can't create temporary dir" >&2
	exit 255
fi

trap 'rm -r -f "$TMP_HOSTNAME_DIR"' EXIT

echo $HOSTNAME > "$TMP_HOSTNAME_DIR/HOSTNAME"
if [ $? -ne 0 ]; then
	echo "Can't write hostname to $TMP_HOSTNAME_DIR/HOSTNAME" >&2
	exit 255
fi

TEMPORARY_FILE="/tmp/${SERVICE_NAME}-$$.tar"
if [ -d "$SERVICE_FILES_FOR_DESTINATION" ]
then
	tar -c -f "$TEMPORARY_FILE" -C "$SERVICE_FILES_FOR_DESTINATION" . -C "$SERVICE_FILES_DIR"  --exclude="_destination" .  -C "$TMP_HOSTNAME_DIR" . 
else
	tar -c -f "$TEMPORARY_FILE" -C "$SERVICE_FILES_DIR"  --exclude="_destination" .  -C "$TMP_HOSTNAME_DIR" . 
fi

if [ $? -ne 0 ]; then
	echo "Can't archive service files to $TEMPORARY_FILE" >&2
	exit 255
fi

if [ "$DESTINATION_TYPE"="url" ]; then
	timeout -k $TIMEOUT_KILL $TIMEOUT $TRANSPORT_COMMAND --data-binary @$TEMPORARY_FILE $HOST
else
	cat $TEMPORARY_FILE | timeout -k $TIMEOUT_KILL $TIMEOUT $TRANSPORT_COMMAND $HOST $SLAVE_COMMAND
fi

ERR_CODE=$?

echo "Communication with slave script ends with return code: $ERR_CODE" >&2

exit $ERR_CODE
