#!/bin/bash
SERVICE_NAME="google_groups"

FACILITY_NAME=$1

SERVICE_FILES_BASE_DIR="`pwd`/../gen/spool"
SERVICE_FILES_DIR="$SERVICE_FILES_BASE_DIR/$FACILITY_NAME/$SERVICE_NAME"

#Just safety check. This should not happen.
if [ ! -d "$SERVICE_FILES_DIR" ]; then echo '$SERVICE_FILES_DIR: '$SERVICE_FILES_DIR' is not a directory' >&2 ; exit 1; fi

JAR='/home/perun/perun-google-group-connector/GoogleGroupConnector-2.0.0.jar'
LOGBACK='-Dlogback.configurationFile=/etc/perun/logback-google-groups.xml'

# manage groups
java $LOGBACK -jar $JAR `cat "$SERVICE_FILES_DIR"/google_groups_domain` "groups" "$SERVICE_FILES_DIR/google_groups_groups.csv" || exit 1;
