#!/bin/bash

SERVICE_NAME="myq_printsvc"

TIMEOUT="5400" #90s * 60 sec = 1.5h
TIMEOUT_KILL="60" # 60 sec to kill after timeout

FACILITY_NAME=$1
DESTINATION=$2
DESTINATION_TYPE=$3

SERVICE_FILES_BASE_DIR="`pwd`/../gen/spool"
SERVICE_FILES_DIR="$SERVICE_FILES_BASE_DIR/$FACILITY_NAME/$SERVICE_NAME"

cp -f "$SERVICE_FILES_DIR/import_users-perun.csv" "/mnt/myq-ukb/import_users-perun.csv"