#!/bin/bash
SERVICE_NAME="vsup_google_groups"

FACILITY_NAME=$1

SERVICE_FILES_BASE_DIR="`pwd`/../gen/spool"
SERVICE_FILES_DIR="$SERVICE_FILES_BASE_DIR/$FACILITY_NAME/$SERVICE_NAME"

#Just safety check. This should not happen.
if [ ! -d "$SERVICE_FILES_DIR" ]; then echo '$SERVICE_FILES_DIR: '$SERVICE_FILES_DIR' is not a directory' >&2 ; exit 1; fi

java -Dlogback.configurationFile=file:///etc/perun/logback-google-groups.xml -jar /home/perun/perun-google-group-connector/GoogleGroupConnector-1.0-SNAPSHOT.jar `cat "$SERVICE_FILES_DIR"/vsup_google_groups_domain` "users" "$SERVICE_FILES_DIR/vsup_google_groups_users.csv"

java -Dlogback.configurationFile=file:///etc/perun/logback-google-groups.xml -jar /home/perun/perun-google-group-connector/GoogleGroupConnector-1.0-SNAPSHOT.jar `cat "$SERVICE_FILES_DIR"/vsup_google_groups_domain` "groups" "$SERVICE_FILES_DIR/vsup_google_groups_groups.csv"

exit $?
