#!/usr/bin/make -f

INSTALL = install

build: ;

install:
	$(INSTALL) -d -m 755 $(DESTDIR)/etc/perun/afs_group.d $(DESTDIR)/etc/perun/fs_home.d $(DESTDIR)/etc/perun/fs_project.d $(DESTDIR)/etc/perun/fs_quotas.d $(DESTDIR)/etc/perun/fs_scratch.d $(DESTDIR)/etc/perun/fs_scratch_local.d $(DESTDIR)/etc/perun/pbs_phys_cluster.d
