#!/bin/bash

### BEGIN INIT INFO
# Provides:          perun-propagate
# Required-Start:    $local_fs $remote_fs $network sshd
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Perun propagate
# Description:       Start the perun propagate process
### END INIT INFO

NAME=perun-propagate
DESC="Perun propagation"
PERUN_SERVER='perun.ics.muni.cz'
TIMEOUT=120
LOG=/var/log/$NAME
KEYTAB=/etc/krb5.keytab

umask 077

# Include defaults if available
if [ -f /etc/default/$NAME ] ; then
	. /etc/default/$NAME
fi

# Load lsb functions
. /lib/lsb/init-functions

check() {
	for C in ktutil kinit remctl; do
		which "${C}" &>/dev/null || {
			log_progress_msg "missing ${C}"
			return 1
		}
	done
}

perun_propagate_start() {
	CC_FILE=`mktemp`
	trap "unlink ${CC_FILE}" ERR
	export KRB5CCNAME="FILE:${CC_FILE}"

	set -e
	if ktutil --version </dev/null 2>&1 | grep -qi heimdal; then
		# Heimdal
		PRINCIPAL=`ktutil list 2>/dev/null | awk '($3~"^host/") && ($3!~"\\\.ipv6\\\.") { print $3 }' | head -1`
		kinit --no-afslog --keytab="${KEYTAB}" "${PRINCIPAL}"
	else
		# MIT Kerberos
		PRINCIPAL=`echo -e "read_kt ${KEYTAB}\nlist" | ktutil list 2>/dev/null | awk '($3~"^host/") && ($3!~"\\\.ipv6\\\.") { print $3 }' | head -1`
		kinit -k -t "${KEYTAB}" "${PRINCIPAL}"
	fi

	set +e
	if which timeout stdbuf &>/dev/null; then
		OUT=`timeout ${TIMEOUT} stdbuf -oL -eL remctl "${PERUN_SERVER}" perun propagate 2>&1`
		EXIT_CODE=$?
	else
		OUT=`remctl "${PERUN_SERVER}" perun propagate 2>&1`
		EXIT_CODE=$?
	fi

	kdestroy &>/dev/null

	trap - ERR
	echo "${OUT}" >"${LOG}"
	[ ${EXIT_CODE} -ne 0 ] && echo "${OUT}" >&2
	return ${EXIT_CODE}
}


case "$1" in
	start)
		# Check if krb5.keytab exists
		test ! -f "${KEYTAB}" && log_failure_msg "keytab missing" && exit 0 # Quit silently
		
		log_daemon_msg "Starting $DESC" "$NAME"
		check && perun_propagate_start
		log_end_msg $?
		;;

	stop|force-stop|restart|force-reload|status)
		exit 0
		;;

	*)
		echo "Usage: $0 {start|stop|force-stop|restart|force-reload|status}" >&2
		exit 2
		;;
esac
